name: CI

on:
  push:
    branches: [dev, beta, master]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev]

jobs:
  # A fast overview job that checks only changed files
  overview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache pip modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: esphome-pip-3.8-${{ hashFiles('setup.py') }}
          restore-keys: |
            esphome-pip-
      - name: Cache Platformio
        uses: actions/cache@v1
        with:
          path: ~/.platformio
          key: esphome-platformio
      - name: Setup environment
        run: |
          script/setup
          pio init --ide atom
      - name: Run a quick lint over all changed files
        uses: esphome/esphome-lint-action@v1
        with:
          run: |
            script/quicklint
            script/ci-suggest-changes

  # Full CI
  cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache pip modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: esphome-pip-3.8-${{ hashFiles('setup.py') }}
          restore-keys: |
            esphome-pip-
      - name: Cache Platformio
        uses: actions/cache@v1
        with:
          path: ~/.platformio
          key: esphome-platformio
      - name: Setup environment
        run: |
          script/setup
          pio init --ide atom
      - name: Lint Cpp Code
        uses: esphome/esphome-lint-action@v1
        with:
          run: |
            script/clang-tidy --all-headers --fix
            script/clang-format -i
            script/ci-suggest-changes

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Cache pip modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: esphome-pip-3.7-${{ hashFiles('setup.py') }}
          restore-keys: |
            esphome-pip-
      - name: Cache Platformio
        uses: actions/cache@v1
        with:
          path: ~/.platformio
          key: esphome-platformio
      - name: Setup environment
        run: |
          script/setup
      - name: Lint Python
        run: |
          script/ci-custom.py
          flake8 esphome
          pylint esphome

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          test:
          - test1
          - test2
          - test3
          - test4
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Cache pip modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: esphome-pip-3.6-${{ hashFiles('setup.py') }}
          restore-keys: |
            esphome-pip-
      - name: Cache Platformio
        uses: actions/cache@v1
        with:
          path: ~/.platformio
          key: esphome-platformio
      - name: Setup environment
        run: |
          script/setup
      - run: |
          esphome tests/${{ matrix.test }}.yaml compile
